CREATE DATABASE FNESITE;

USE FNESITE;

-- -- -- -- -- -- -- --
-- -- -- -- -- -- -- -- USER ZONE

-- UTILISATEURS
CREATE TABLE USER   (
	USER_ID      INT AUTO_INCREMENT PRIMARY KEY,
	ROLE        INT NOT NULL,
	NAME           VARCHAR(50) NOT NULL,
    SURNAME        VARCHAR(50) NOT NULL,
    MAIL         VARCHAR(100) NOT NULL,
    ADRESS          VARCHAR(250) NOT NULL,
    CP           INT  NOT NULL,
    PROFESSION    VARCHAR(50) NOT NULL,
    PROFESSION2   VARCHAR(50),
    PRESENTATION BLOB,
    PHOTOPATH     VARCHAR(50)       
);

-- THEMATIQUES (EAU, SANTE, ETC...)
CREATE TABLE THEME   (
    THEME_ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100) NOT NULL
);

-- TERRITOIRE (ETANG DE TRUC, ETC...)
CREATE TABLE TERRITORY   (
    TERRITORY_ID   INT AUTO_INCREMENT PRIMARY KEY,
    NAME              VARCHAR(100) NOT NULL
);

-- LIENS USERS/THEMATIQUES
CREATE TABLE USER_THEME   (
    USER_ID         INT NOT NULL,
    THEME_ID        INT NOT NULL,
    
    CONSTRAINT FK_USERTHEME_US FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_USERTHEME_TH FOREIGN KEY (THEME_ID) REFERENCES THEME(THEME_ID)
);

-- LIENS USERS/TERRITOIRE
CREATE TABLE USER_TERRITOIRE   (
    USER_ID         INT NOT NULL,
    TERRITORY_ID   INT NOT NULL,
    
    CONSTRAINT FK_USERTERRITORY_US FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID),
    CONSTRAINT FK_USERTERRITORY_TE FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORY(TERRITORY_ID)
);

-- -- -- -- -- --
-- -- -- -- -- -- MESSAGES ZONE

-- MESSAGES PRIVES STOCKES
CREATE TABLE MESSAGES  (
    MSG_ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SENDER          INT NOT NULL,
    RECEIVER        INT NOT NULL,
    TITLE           VARCHAR(150) NOT NULL,
    CONTENT         BLOB NOT NULL,
    
    CONSTRAINT FK_MESSAGE_SENDER FOREIGN KEY (SENDER) REFERENCES USER(USER_ID),
    CONSTRAINT FK_MESSAGE_RECEIVER FOREIGN KEY (RECEIVER) REFERENCES USER(USER_ID)
);


-- -- -- -- -- --
-- -- -- -- -- -- ARTICLES ZONE

-- ARTICLES STOCKES
CREATE TABLE POST (
    POST_ID       INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WRITER        INT NOT NULL,
    TITLE         VARCHAR(150) NOT NULL,
    PDATE         DATE NOT NULL,
    DURATION      INT,
    CONTENT       LONGTEXT,
    
    CONSTRAINT FK_POSTWRITER FOREIGN KEY (WRITER) REFERENCES USER(USER_ID)
);


-- -- -- -- -- --
-- -- -- -- -- -- RAPPORT ZONE

-- RAPPORTS D'ACTIONS
CREATE TABLE REPORT (
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RDATE   DATE NOT NULL,
    TYPE    INT,
    CONTENT VARCHAR(300)
);


-- -- -- -- -- --
-- -- -- -- -- -- NL ZONE

-- NEWSLETTERS
CREATE TABLE NEWSLETTER (
    NL_ID INT AUTO_INCREMENT PRIMARY KEY,
    NL_DATE DATE NOT NULL,
    NL_CONTENT LONGTEXT,
    NL_PATH VARCHAR(200)
);
