DROP DATABASE FNESITE;
CREATE DATABASE FNESITE DEFAULT CHARACTER SET UTF8;
USE FNESITE;

/* THEME (EAU, SANTE, ETC...) */
CREATE TABLE THEME   (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL
);

/* TERRITORY (ETANG DE TRUC, ETC...) */ 
CREATE TABLE TERRITORY   (
    ID          INT AUTO_INCREMENT PRIMARY KEY,
    NAME        VARCHAR(100) NOT NULL
);

/* ASSOCIATION */
CREATE TABLE ASSOCIATION (
    ID              INT AUTO_INCREMENT PRIMARY KEY,
    NAME            VARCHAR(100),
    TERRITORY_ID    INT NOT NULL,
    
    CONSTRAINT FK_ASSOTERRITORY FOREIGN KEY (TERRITORY_ID) REFERENCES TERRITORY(ID)
);

/* USER */
CREATE TABLE USER   (
	ID                  INT AUTO_INCREMENT PRIMARY KEY,
	LOGIN               VARCHAR(50) NOT NULL,
	PASSWORD            VARCHAR(100) NOT NULL,
	RESET               VARCHAR(100) DEFAULT NULL, 
	ASSOCIATION_ID      INT NOT NULL,
	THEME_ID            INT,
	THEME_INTEREST_ID   INT,
	THEME_DETAILS       VARCHAR(250),
	ROLE                VARCHAR(50) NOT NULL,
	NAME                VARCHAR(100) NOT NULL,
    SURNAME             VARCHAR(100) NOT NULL,
    MAIL                VARCHAR(100) NOT NULL,
    ADRESS              VARCHAR(250) NOT NULL,
    CP                  INT NOT NULL,
    PROFESSION          VARCHAR(100) NOT NULL,
    PROFESSION2         VARCHAR(100),
    PRESENTATION        BLOB,
    PHOTOPATH           VARCHAR(50),

    CONSTRAINT FK_USER_THEME FOREIGN KEY (THEME_ID) REFERENCES THEME(ID),
    CONSTRAINT FK_USER_THEMEINT FOREIGN KEY (THEME_INTEREST_ID) REFERENCES THEME(ID),
    CONSTRAINT FK_USER_ASSOCID FOREIGN KEY (ASSOCIATION_ID) REFERENCES ASSOCIATION(ID)
);


/* MESSAGES */
CREATE TABLE MESSAGE  (
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    SENDER_ID       INT NOT NULL,
    RECEIVER_ID     INT NOT NULL,
    ISREAD          BOOLEAN,
    SENDDATE        DATE,          
    TITLE           VARCHAR(150) NOT NULL,
    CONTENT         BLOB NOT NULL,
    
    CONSTRAINT FK_MESSAGE_SENDER FOREIGN KEY (SENDER_ID) REFERENCES USER(ID),
    CONSTRAINT FK_MESSAGE_RECEIVER FOREIGN KEY (RECEIVER_ID) REFERENCES USER(ID)
);


/* POST */
/* Attribut TYPE :"ARTICLE" ou "AGENDA" */
CREATE TABLE POST (
    ID          INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    WRITER_ID   INT NOT NULL,
    TITLE       VARCHAR(150) NOT NULL,
    DESCRIPTION VARCHAR(200),
	PTYPE		VARCHAR(50),
    PDATE       DATE NOT NULL,
    DURATION    INT,
    CONTENT     LONGTEXT,
    STATUS      INT,       
    IMAGEPATH   VARCHAR(150),
    
    CONSTRAINT FK_POSTWRITER FOREIGN KEY (WRITER_ID) REFERENCES USER(ID)
);


/* REPORT */
/* Attribut TYPE : "PROFIL" ou "ARTICLE" ou "MESSAGE" */
CREATE TABLE REPORT (
    ID      INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    RDATE   DATE NOT NULL,
    TYPE    VARCHAR(50),
    CONTENT VARCHAR(300)
);


/* NEWSLETTER */
CREATE TABLE NEWSLETTER (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NLDATE DATE NOT NULL,
    CONTENT LONGTEXT,
    PATH VARCHAR(200)
);

/* LOGINFAIL */
CREATE TABLE LOGINFAIL (
	ID_USER INT PRIMARY KEY,
	IP VARCHAR(50),
	EXPIRE TIMESTAMP,
	ATTEMPTS SMALLINT
);

/* *********** */
/* JEU DE TEST */
/* *********** */

/* Données à conserver (probablement) */

/* Thématiques (8) */
INSERT INTO THEME (NAME) VALUES ('Transports');
INSERT INTO THEME (NAME) VALUES ('Mission Juridique');
INSERT INTO THEME (NAME) VALUES ('Climat, Air, Energie');
INSERT INTO THEME (NAME) VALUES ('Santé Environnement');
INSERT INTO THEME (NAME) VALUES ('Aménagement durable du territoire');
INSERT INTO THEME (NAME) VALUES ('Industrie');
INSERT INTO THEME (NAME) VALUES ('Eau et milieux naturels');
INSERT INTO THEME (NAME) VALUES ('Agriculture');

/* Territoires (5) */
INSERT INTO TERRITORY (NAME) VALUES ('Vallée du Rhône');
INSERT INTO TERRITORY (NAME) VALUES ('Vallée de l\'Huveaune');
INSERT INTO TERRITORY (NAME) VALUES ('Les Alpilles');
INSERT INTO TERRITORY (NAME) VALUES ('Etang de Berre, Fos-sur-Mer');
INSERT INTO TERRITORY (NAME) VALUES ('Métropole Marseille');

/* Données pour tests */

/* ASSO 1 - Nom - FNE13 */
/* ASSO 2 - Nom - TrucAsso */
/* ASSO 3 - Nom - MachinAsso */
/* ASSO 4 - Nom - BiduleAsso */
INSERT INTO ASSOCIATION(NAME, TERRITORY_ID) VALUES ('FNE13' , 1);
INSERT INTO ASSOCIATION(NAME,  TERRITORY_ID) VALUES ('TrucAsso', 2);
INSERT INTO ASSOCIATION(NAME,  TERRITORY_ID) VALUES ('MachinAsso', 3);
INSERT INTO ASSOCIATION(NAME,  TERRITORY_ID) VALUES ('BiduleAsso', 4);

/* USER 1 - Nicolas Damien (rôle SADMIN dans la FNE13) */
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('nicolas.damien','mdp',1,NULL,NULL,NULL,'SADMIN','Damien','Nicolas','nicolas.damien@truc.fr','33 Somewhere over the rainbow','13000','Directeur',NULL,'Bonjour !','../Photos/nicdam.png');

/* USER 2 - Huguette1 Dupont1 (role MEMBRE dans TrucAsso, spécialiste Santé, intéressée Agriculture) */ 
/* USER 3 - Huguette2 Dupont2 (role MEMBRE dans MachinAsso, intéressée Transports) */ 
/* USER 4 - Huguette3 Dupont3 (role VALIDATOR dans BiduleAsso,intéressée Industrie) */
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('huguette1','mdp',2, 4, 8, 'Infirmerie','MEMBRE','Dupont1','Huguette1','huguette1@machin.com','11 Highway to hell','13001','Infirmière','Retraitée','Bonjour tout le monde. Signé : Huguette1','../Photos/huguette1.png');
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('huguette2','mdp',3, NULL, 1,NULL,'MEMBRE','Dupont2','Huguette2','huguette2@machin.com','22 Highway to hell','13002','Secrétaire','Retraitée','Bonjour tout le monde. Signé : Huguette2','../Photos/huguette2.png');
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('huguette3','mdp',4,NULL,6,NULL,'VALIDATOR','Dupont3','Huguette3','huguette3@machin.com','33 Highway to hell','13003','Chirurgienne','Retraitée','Bonjour tout le monde. Signé : Huguette3','../Photos/huguette3.png');

/* USER 5 - Francis1 Dupond1 (role ADMIN dans TrucAsso, specialiste Eau, intéressé Santé) */
/* USER 6 - Francis2 Dupond2 (role ADMIN dans MachinAsson, specialiste Agriculture, intéressé Transports) */
/* USER 7 - Francis3 Dupond3 (role ADMIN dans BiduleAsso, intéressé Santé) */
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('francis1','mdp',2, 7, 4,'Barrages hydroliques','ADMIN','Dupond1','Francis1','francis1@truc.fr','01 Quelque part','19000','Ingénieur Eau',NULL,'...1','../Photos/francis1.png'); 
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('francis2','mdp',3, 8, 1,'Plantations','ADMIN','Dupond2','Francis2','francis2@truc.fr','02 Quelque part','29000','Ingénieur Terre',NULL,'...2','../Photos/francis2.png'); 
INSERT INTO USER (LOGIN, PASSWORD, ASSOCIATION_ID, THEME_ID, THEME_INTEREST_ID, THEME_DETAILS, ROLE, NAME, SURNAME, MAIL, ADRESS, CP, PROFESSION, PROFESSION2, PRESENTATION, PHOTOPATH) 
          VALUES ('francis3','mdp',4, NULL,4,NULL,'ADMIN','Dupond3','Francis3','francis3@truc.fr','03 Quelque part','39000','Ingénieur Air',NULL,'...3','../Photos/francis3.png'); 

/* RAPPORTS */
INSERT INTO REPORT VALUES (NULL, "2014/12/20", "PROFIL", "HUGUETTE A CHANGE SON PROFIL -> CHAMP DESCRIPTION");
INSERT INTO REPORT VALUES (NULL, "2014/11/20", "ARTICLE", "HUGUETTE A VALIDE L ARTICLE BLABLA");
INSERT INTO REPORT VALUES (NULL, "2014/10/20", "MESSAGE", "HUGUETTE A CONTACTE FRANCIS");

/* MESSAGES */
INSERT INTO MESSAGE VALUES (NULL, 1, 2, FALSE, "2015/01/01", "IMMA TITLE", "BONJOUR !");
